name: Build all docker images

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 3 * * *'
  pull_request:
    branches:
    - "main"
    - "dev"
  push:
    branches:
    - '!test*'
    - "**"
    tags:
    - "v*.*.*"
  release:
    types: [created]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  packages: write

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

      # Get the repository's code
      - name: Checkout
        uses: actions/checkout@v4
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        #with:
        #  driver-opts: |
        #    image=moby/buildkit:v0.12.3


      - name: Login to the GitHub Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/papamoose/container-mariadb-backup
          # generate Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=raw,${{ github.event.release.tag_name }}
            type=raw,value=latest,enable=${{ github.event_name == 'release' }}
          labels: |
            maintainer=papamoose
            org.opencontainers.image.title=Backup MariaDB
            org.opencontainers.image.description=Alpine with cron to run mysqldump
            org.opencontainers.image.vendor=Papamoose Co

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
